services:
  app-dev:
    image: excel-web-fe
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    container_name: excel-web-fe

  # app-prod: 
  #     container_name: "excel-web-fe"
  #     image: "excel-web-fe"
  #     build:
  #       context: .
  #       dockerfile: Dockerfile.prod
  #     ports:
  #       - 8082:80
