export const constants = {
	DATA_MANAGEMENT_SYSTEM: 'Data Management System',
	AUTH_LEFT_SCREEN_SUBTITLE: 'Bringing your Excel files together effortlessly with Excelinsight',
	SIGN_UP: 'Sign Up',
	LOG_IN: 'Log In',
	RESET_PASSWORD: 'Reset Password',
	RESET_PASSWORD_SUBTITLE: 'Should minimum of 8 characters',
	ENTER_CREDENTIALS_MESSAGE: 'Please enter your credential here.',
	FORGOT_PASSWORD_PROMPT: 'Forgot password?',
	FORGOT_MY_PASSWORD_TITLE: 'Forgot My Password',
	SENT_OTP_PROMPT: 'We have sent a OTP to your mail to reset your password',
	FORGOT_MY_PASSWORD_SUBTITLE: 'Input your email below to receive a password reset link to your inbox',
	KYC_TITLE: 'Tell Us About Yourself',
	KYC_TITLE_SUBTITLE: 'To customize your experience!',
}